@baseUrl = http://localhost:3333

# @name create_account

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Nailson Israel",
  "email": "nailson.ivs@gmail.com",
  "password": "12345"
}

###